name: Github JavaScript Actions CI

on:
  push:
    branches:
    - '**'
  pull_request:
    types: [closed]

jobs:
  build:
    name: Continuous Integration
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.x' # SDK Version to use; x will use the latest version of the 3.1 channel
    - run: dotnet build

    - name: Establish context
      id: context
      uses: ./ # Replace with ./ if used withing dolittle/establish-context-action

    - name: Increment version
      id: increment-version
      if: ${{ steps.context.outputs.should-publish == 'true' }}
      uses: dolittle/increment-version-action@v2 # Replace with ./ if used withing dolittle/increment-version-action
      with:
        version: ${{ steps.context.outputs.current-version }}
        release-type: ${{ steps.context.outputs.release-type }}

    - name: Create packages
      

    - name: Create GitHub Release
      if: ${{ steps.context.outputs.should-publish == 'true' }}
      uses: dolittle/github-release-action@v1 # Replace with ./ if used withing dolittle/github-release-action
      with:
        token: ${{  secrets.BUILD_PAT  }}
        cascading-release: ${{ steps.context.outputs.cascading-release }}
        version: ${{ steps.increment-version.outputs.next-version }}
