name: Contracts CI/CD

env:
  PRERELEASE_BRANCHES: alpha,beta,rc,updategrpc # Comma separated list of prerelease branch names. 'alpha,rc, ...'

on:
  push:
    branches:
    - '**'
  pull_request:
    types: [closed]

jobs:
  context:
    name: Setup context for release
    runs-on: ubuntu-latest
    outputs:
      should-publish: ${{ steps.context.outputs.should-publish }}
      pr-body: ${{ steps.context.outputs.pr-body }}
      pr-url: ${{ steps.context.outputs.pr-url }}
      version: ${{ steps.increment-version.outputs.next-version }}

    steps:
    - uses: actions/checkout@v2
    - name: Establish context
      id: context
      uses: dolittle/establish-context-action@v2 # Replace with ./ if used withing dolittle/establish-context-action
      with:
        prerelease-branches: ${{ env.PRERELEASE_BRANCHES }}
    - name: Increment version
      id: increment-version
      if: ${{ steps.context.outputs.should-publish == 'true' }}
      uses: dolittle/increment-version-action@v2 # Replace with ./ if used withing dolittle/increment-version-action
      with:
        version: ${{ steps.context.outputs.current-version }}
        release-type: ${{ steps.context.outputs.release-type }}

  dot-net-build:
    name: .Net Build
    runs-on: ubuntu-latest
    needs: context

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.1.x'
      - run: dotnet build -c Release

  release:
    name: Release
    runs-on: ubuntu-latest
    needs: [dot-net-build, context]
    if: ${{ needs.context.outputs.should-publish == 'true' }}

    steps:
    - uses: actions/checkout@v2
    - name: Prepend to Changelog
      uses: dolittle/add-to-changelog-action@v2
      with:
        version: ${{ needs.context.outputs.version }}
        body: ${{ needs.context.outputs.pr-body }}
        pr-url: ${{ needs.context.outputs.pr-url }}
        changelog-path: CHANGELOG.md
        user-email: build@dolittle.com
        user-name: dolittle-build
    - name: Create GitHub Release
      uses: dolittle/github-release-action@v2 # Replace with ./ if used withing dolittle/github-release-action
      with:
        version: ${{ needs.context.outputs.version }}
        body: ${{ needs.context.outputs.pr-body }}

  dot-net-release:
    name: .Net Release
    runs-on: ubuntu-latest
    needs: [context, dot-net-build]
    if: ${{ needs.context.outputs.should-publish == 'true' }}

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.1.x'
      - run: dotnet build
      - name: Create packages
        run: dotnet pack --configuration Release -o Artifacts/NuGet /p:PackageVersion=${{ needs.context.outputs.version }} -p:IncludeSymbols=true -p:SymbolPackageFormat=snupkg -p:NoDefaultExcludes=true
      - name: Push NuGet packages
        run: dotnet nuget push 'Artifacts/NuGet/*.nupkg' --skip-duplicate --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json

  # java-script:
  #   name: JavaScript
  #   runs-on: ubuntu-latest
  #   needs: context

  #   steps:
  #   - uses: actions/checkout@v2
  #   - uses: actions/setup-node@v1
  #     with:
  #       node-version: 12.x
  #   - uses: arduino/setup-protoc@master
  #     with:
  #       version: '3.11.2'

  #   - name: Install dependencies
  #     working-directory: ./Generation
  #     run: yarn

  #   - name: Build Fundamentals
  #     working-directory: ./Generation/Fundamentals/JavaScript
  #     run: yarn build
  #   - name: Build Fundamentals Web
  #     working-directory: ./Generation/Fundamentals/JavaScript.Web
  #     run: yarn build
  #   - name: Build Runtime
  #     working-directory: ./Generation/Runtime/JavaScript
  #     run: yarn build
  #   - name: Build Runtime Web
  #     working-directory: ./Generation/Runtime/JavaScript.Web
  #     run: yarn build

  #   - name: Publish Fundamentals
  #     if: ${{ success() && needs.context.outputs.should-publish == 'true' }}
  #     working-directory: ./Generation/Fundamentals/JavaScript
  #     run: yarn publish --new-version ${{ needs.context.outputs.version }} --no-git-tag-version
  #   - name: Publish Fundamentals Web
  #     if: ${{ success() && needs.context.outputs.should-publish == 'true' }}
  #     working-directory: ./Generation/Fundamentals/JavaScript.Web
  #     run: yarn publish --new-version ${{ needs.context.outputs.version }} --no-git-tag-version
  #   - name: Publish Runtime
  #     if: ${{ success() && needs.context.outputs.should-publish == 'true' }}
  #     working-directory: ./Generation/Runtime/JavaScript
  #     run: yarn publish --new-version ${{ needs.context.outputs.version }} --no-git-tag-version
  #   - name: Publish Runtime Web
  #     if: ${{ success() && needs.context.outputs.should-publish == 'true' }}
  #     working-directory: ./Generation/Runtime/JavaScript.Web
  #     run: yarn publish --new-version ${{ needs.context.outputs.version }} --no-git-tag-version

  #   - name: Create Pull Request
  #     if: ${{ success() && needs.context.outputs.should-publish == 'true' }}
  #     uses: peter-evans/create-pull-request@v2
  #     with:
  #       title: Bump package.json versions to ${{ needs.context.outputs.version }}
